language: node_js
node_js:
 - "node"
 env:
  global:
    - CC_TEST_REPORTER_ID=28cf2ec7cd2a529818feebdc466d27305f71c3e6a56b03bc22f37ed4b7e40716

addons:
  code_climate:
    repo_token: 28cf2ec7cd2a529818feebdc466d27305f71c3e6a56b03bc22f37ed4b7e40716

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run testb
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT